package Tests;

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class Signuptest {

    @Test
    public void testregisteruser(){
        System.setProperty("webdriver.chrome.driver", "C:\\Users\\robso\\Drivers\\chromedriver.exe");

        WebDriver driver = new ChromeDriver();

        //Information: This cases test is about registering of user on the Facebook.

        //Open the browser "http://www.facebook.com"
        driver.get("http://www.facebook.com");

        //Digit in the field Name = "Robson" that contain name = firstname
        driver.findElement(By.name("firstname")).sendKeys("Robson");

        //Digit in the field LastName = "Laurindo" that contain name = lastname
        driver.findElement(By.name("lastname")).sendKeys("Laurindo");

        //Digit in the field mobile or email = "email@gmail.com" that contain id = reg_email__
        driver.findElement(By.id("u_0_t")).sendKeys("email@gmail.com");

        //Digit in the field the confirmation about email = "email@gmail.com" that contain id = u_0_w
        driver.findElement(By.id("u_0_w")).sendKeys("email@gmail.com");

        //Digit a new password = "teste123@" that contain id = password_step_input
        driver.findElement(By.id("password_step_input")).sendKeys("*******");

        //Select the value for day = 10 that contain id = day
        driver.findElement(By.id("day")).sendKeys("10");

        //Select the value for month = 09 that contain id = month
        driver.findElement(By.id("month")).sendKeys("09");

        //Select the value for year = 1986 that contain id = year
        driver.findElement(By.id("year")).sendKeys("1986");

        //Select the value = male that contain id = u_0_7
        WebElement radio2 = driver.findElement(By.id("u_0_7"));
        radio2.click();
        System.out.println("Radio Button Option 2 Selected");

        //To do sign up
        driver.findElement(By.id("u_0_15")).click();

        //insert the code = 85545 inside of field with id = code_in_cliff
        driver.findElement(By.id("code_in_cliff")).sendKeys("85545");

        //Click on "confirm" button that contain the following id = u_8_h
        driver.findElement(By.id("u_8_h")).click();

        //Close the browser
        //driver.close();
